### ISSUE TITLE
URLs in attributes can cause exceptions

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-net#83]
Template: `UGGRoyale.mjml` and `Arturia.mjml`

There is a `<mj-text>` which contains an `<a>` with the `href`:

```html
<!-- UGGRoyale.mjml -->
<a href="https://email.ugg.com/pub/sf/ResponseForm?_ri_=X0Gzc2X%3DYQpglLjHJlTQGjmR9kDzfwzbMzackp9f3F8d45ze2zfbW8hYB6AzgB7gaIYB3tN5qwvasVXMtX%3DYQpglLjHJlTQGNXlMNF3fFUYHWCzdBj2rGzgJpzem2KonGoezgzbfUyABevzgl4CepTMC&_ei_=EolaGGF4SNMvxFF7KucKuWP7XpARYKtbBY43fLBYxvXNpGx2Z89j4M" style="text-decoration:underline; color:#111111;">View in Browser</a>

<!-- Arturia.mjml -->
<a href="https://www.arturia.com/index.php?option=com_myarturia&view=newsletter&task=unsubscribeFromEmail&email={email}&token={title}&utm_source=elasticemail&utm_medium=email&utm_campaign=arturia_unsubscribe_2016&utm_term=nl-ispark-launch&utm_content=unsubscribe_footer" style="text-decoration:none;color:#2DDCB4">Unsubscribe</a>
```
Any URL parameter due to the & is being recognised as XML External Entity.  
```
&_ei_=
&view=
&task=
```

```
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 202, position 230.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlWriter.WriteNode(XmlReader reader, Boolean defattr)
   at System.Xml.XmlReader.ReadOuterXml()
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-net\Mjml.Net\MjmlRenderContext.cs:line 130
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-net\Mjml.Net\MjmlRenderContext.cs:line 148
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-net\Mjml.Net\MjmlRenderContext.cs:line 148
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-net\Mjml.Net\MjmlRenderContext.cs:line 148
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-net\Mjml.Net\MjmlRenderContext.cs:line 148
   at Mjml.Net.MjmlRenderContext.Read(XmlReader reader) in C:\Source\mjml-net\Mjml.Net\MjmlRenderContext.cs:line 58
   at Mjml.Net.MjmlRenderer.Render(XmlReader xml, MjmlOptions options) in C:\Source\mjml-net\Mjml.Net\MjmlRenderer.cs:line 111
   at Mjml.Net.MjmlRenderer.Render(String mjml, MjmlOptions options) in C:\Source\mjml-net\Mjml.Net\MjmlRenderer.cs:line 87
   at Mjml.Net.Benchmarking.TestRunner.Run(String fileName, String filePath, MjmlRenderer mjmlRenderer) in C:\Source\mjml-net\Mjml.Net.Benchmark\TestRunner.cs:line 47
   at Mjml.Net.Benchmarking.TestRunner.Run(Int32 numberOfIterations) in C:\Source\mjml-net\Mjml.Net.Benchmark\TestRunner.cs:line 31
```

This issue is important as users would need to URL Encode.

**Comment by LiamRiddell** [comment]
I think on this one, it could be another limitation of XmlReader unfortunately.  It may need to join the `Known Issues` section in Readme as it's an extension of Entity issue.

**Comment by SebastianStehle** [comment]
Perhaps we need a compatibility mode where we preprocess the html

**Comment by SebastianStehle** [comment]
Or just a simple string converter. I would like to allow my users this quirks and then save the cleaned version in the DB.

**Comment by LiamRiddell** [comment]
> Or just a simple string converter. I would like to allow my users this quirks and then save the cleaned version in the DB.

I think string converter utility would be better. Then we expose it and allow the user to handle how and when they use it. 

That way it allows users to optimise templates by fixing them at source fixing HTML Character Entities and encoding URLs but if there not sure how then the string converter can do it for you at the cost of compilation speed.

**Comment by SebastianStehle** [comment]
I have fixed that with a cleaner.

**Comment by cm-andrews** [comment]
> I have fixed that with a cleaner.

Just running into this issue in 1.11.0. Does the package contain a fix for this issue or should be clean the Urls ourselves?

**Comment by SebastianStehle** [comment]
You can use the method "FixXML" for that. I have updated the Readme.
